#+title: Cheat Sheet
SPC h k <keybinding> = M-x helpful-key <keybinding> = will tell you the emacs command behind a keybinding.
SPC h c <keybinding> = M-x describe-key-briefly <keybinding> = will tell you mini info about doom emacs command that is called.
:h :<cmd> = M-x +evil:help :<cmd> = evil help, get info about a : command
C-h f <function> RET = will give you the documentation of a function
C-h v <variable> RET = will tell you the value of a variable


M-x = SPC : = run elisp command

SPC . = open file

Neat:
SPC t l = rotate through line number settings, relative -> t -> relative -> nil

Frame related:
SPC q f = delete frame (for eg. when opening two emacs frames with e)

Buffer related:
SPC b n = :bn = C-x RIGHT = next user buffer (or new if none exists)
SPC b p = :bp = C-x LEFT = previous user buffer (or new if none exists)
SPC b l = C-x b RET = swap back to the last opened buffer.
SPC b N = C-x b <new-name> RET = CMD+N = create new fundamental buffer
SPC b b = list workspace buffers
SPC b B = C-x b = list user buffers + system buffers
:ls = old vim style list all buffers
SPC b s = :w = save buffer
SPC b k|d = :bd = kill buffer
SPC b m = create bookmark (stored in bookmark-default-file)

SPC s B = search in all buffers

These command add files to workspace:
SPC SPC = open file in  workspace (projectile.el)
SPC f f = C-x C-f = find open file (files.el)
SPC ENTER = open bookmark

windows:
C-w v = SPC w v = :vsplit = C-x 3 = split vertically (vim like)
C-w s = SPC w s = :split = C-x 2 = split horizontally (vim like)
C-w d = SPC w c|d = :q = C-x 0 = delete window => sometimes ESC or q if temporary window
