("abscissa Cell properties" "426")
("abscissa Create web site" "294")
("abscissa Document source tree preferences" "566")
("abscissa Error messages" "0")
("abscissa Macro editor" "211")
("abscissa Macros editor" "0")
("abscissa Notification" "670")
("abscissa Retina screen settings" "681")
("abscissa TeXmacs" "0")
("abscissa TeXmacs:10" "0")
("abscissa TeXmacs:2" "0")
("abscissa TeXmacs:3" "0")
("abscissa TeXmacs:4" "25")
("abscissa TeXmacs:5" "0")
("abscissa TeXmacs:6" "0")
("abscissa TeXmacs:7" "0")
("abscissa TeXmacs:8" "575")
("abscissa TeXmacs:9" "0")
("abscissa User preferences" "391")
("complex actions" "popups")
("developer tool" "on")
("focus dependent icons" "on")
("height Cell properties" "540")
("height Create web site" "218")
("height Document source tree preferences" "261")
("height Error messages" "1084")
("height Macro editor" "749")
("height Macros editor" "1166")
("height Notification" "147")
("height Retina screen settings" "170")
("height TeXmacs" "1084")
("height TeXmacs:10" "1084")
("height TeXmacs:2" "1084")
("height TeXmacs:3" "1084")
("height TeXmacs:4" "1084")
("height TeXmacs:5" "1084")
("height TeXmacs:6" "1084")
("height TeXmacs:7" "1084")
("height TeXmacs:8" "964")
("height TeXmacs:9" "628")
("height User preferences" "767")
("keyboard tool" "off")
("look and feel" "macos")
("markup gui" "off")
("mathml->texmacs:latex-annotations" "off")
("ordinate Cell properties" "319")
("ordinate Create web site" "424")
("ordinate Document source tree preferences" "410")
("ordinate Error messages" "33")
("ordinate Macro editor" "12")
("ordinate Macros editor" "33")
("ordinate Notification" "373")
("ordinate Retina screen settings" "504")
("ordinate TeXmacs" "33")
("ordinate TeXmacs:10" "33")
("ordinate TeXmacs:2" "33")
("ordinate TeXmacs:3" "33")
("ordinate TeXmacs:4" "33")
("ordinate TeXmacs:5" "33")
("ordinate TeXmacs:6" "33")
("ordinate TeXmacs:7" "33")
("ordinate TeXmacs:8" "33")
("ordinate TeXmacs:9" "33")
("ordinate User preferences" "206")
("page medium" "papyrus")
("presentation tool" "off")
("retina-scale" "2")
("search-and-replace" "off")
("semantic editing" "off")
("shift-0" "A")
("shift-1" "S")
("shift-11" "B")
("shift-12" "Q")
("shift-13" "W")
("shift-14" "E")
("shift-15" "R")
("shift-17" "T")
("shift-18" "+")
("shift-19" "\"")
("shift-2" "D")
("shift-23" "%")
("shift-25" ")")
("shift-26" "/")
("shift-27" "?")
("shift-28" "(")
("shift-29" "=")
("shift-3" "F")
("shift-30" "!")
("shift-31" "O")
("shift-32" "U")
("shift-34" "I")
("shift-35" "P")
("shift-37" "L")
("shift-38" "J")
("shift-4" "H")
("shift-40" "K")
("shift-43" ";")
("shift-44" "_")
("shift-45" "N")
("shift-46" "M")
("shift-47" ":")
("shift-5" "G")
("shift-50" ">")
("shift-6" "Y")
("shift-7" "X")
("shift-8" "C")
("shift-9" "V")
("texmacs->html:images" "off")
("texmacs->html:mathjax" "on")
("texmacs->html:mathml" "off")
("use native menubar" "off")
("user provided icons" "on")
("website:dest-dir" "/Users/deke/Documents/texmacs")
("website:src-dir" "/Users/deke/Documents/texmacs")
("width Cell properties" "875")
("width Create web site" "1140")
("width Document source tree preferences" "595")
("width Error messages" "1728")
("width Macro editor" "1306")
("width Macros editor" "1636")
("width Notification" "437")
("width Retina screen settings" "365")
("width TeXmacs" "1728")
("width TeXmacs:10" "1728")
("width TeXmacs:2" "1728")
("width TeXmacs:3" "1728")
("width TeXmacs:4" "1728")
("width TeXmacs:5" "1728")
("width TeXmacs:6" "1728")
("width TeXmacs:7" "1728")
("width TeXmacs:8" "1153")
("width TeXmacs:9" "800")
("width User preferences" "946")
("zoom factor" "1.0")
